controller_list:
  - name: fake_kuka_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - virtual_joint
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: kuka_arm
    pose: home